cameras:
  front:
    ns: "taluy/cameras/cam_front"
    frame: "taluy/base_link/front_camera_optical_link_stabilized"
    yolo_topic: "/yolo_result_docking"
    handler: "front_camera_handler"
    image_width: 640
    image_height: 480
    id_tf_map:
      0: docking_station_yolo

props:
  docking_station_yolo: {name: "docking_board", real_height: 1.20, real_width: 0.80}

object_groups:
  docking:
    - 0
  all:
    - 0
