---
buttons:
  z_axis_pos:
    index: 5
    gain: 20.0
  z_axis_neg:
    index: 4
    gain: 20.0
  yaw_left:
    index: 1
  yaw_right:
    index: 2

axes:
  x_axis:
    index: [1, 7]
    gain: 20.0
  y_axis:
    index: [0, 6]
    gain: 20.0
