<?xml version="1.0"?>
<robot name="taluy" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="taluy_base">
    <xacro:include filename="$(find auv_common_descriptions)/urdf/actuators.urdf.xacro" />
    <xacro:include filename="$(find auv_common_descriptions)/urdf/materials.urdf.xacro" />

    <link name="base_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="25.0" />
        <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.01" iyz="0.01" ixz="0.1" />
      </inertial>

      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://taluy_description/meshes/body/body.stl"
            scale="1 1 1" />
        </geometry>
        <material name="black" />
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://taluy_description/meshes/body/body.stl"
            scale="1 1 1" />
        </geometry>
      </collision>
    </link>

    <xacro:t200_thruster name="thruster_0" parent="base_link" position="0.14250 0.20070 -0.00525" orientation="0 0 ${-pi/2}"/>
    <xacro:t200_thruster name="thruster_1" parent="base_link" position="0.14250 -0.20070 -0.00525" orientation="0 0 ${pi/2}"/>
    <xacro:t200_thruster name="thruster_2" parent="base_link" position="-0.14250 0.20070 -0.00525" orientation="0 0 ${-pi/2}"/>
    <xacro:t200_thruster name="thruster_3" parent="base_link" position="-0.14250 -0.20070 -0.00525" orientation="0 0 ${pi/2}"/>
    <xacro:t200_thruster name="thruster_4" parent="base_link" position="0.352398 0.216638 -0.030881" orientation="${pi/2} 0 ${pi/4}"/>
    <xacro:t200_thruster name="thruster_5" parent="base_link" position="0.352398 -0.216638 -0.030881" orientation="${-pi/2} 0 ${-pi/4}"/>
    <xacro:t200_thruster name="thruster_6" parent="base_link" position="-0.352398 0.216638 -0.030881" orientation="${pi/2} 0 ${3*pi/4}"/>
    <xacro:t200_thruster name="thruster_7" parent="base_link" position="-0.352398 -0.216638 -0.030881" orientation="${-pi/2} 0 ${-3*pi/4}"/>

    <!-- <link name="base_footprint">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="15.0" />
        <inertia ixx="39.351246" iyy="103.261717" izz="127.702526" ixy="-5e-06" iyz="6e-06"
          ixz="4.403436" />
      </inertial>
    </link>

    <joint name="base_link_joint" type="fixed">
      <origin xyz="0 0 ${-base_z_offsett + 0.06 - draft}" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="base_link" />
    </joint> -->
  </xacro:macro>
</robot>
