velocity_controllers:
  lin_x:
    kp: 35.0
    ki: 0.0
    kd: 5.0
    antiwindup: false
    integrator_clamp: 20.0
    deriv_filter: true
    deriv_filter_alpha: 4.0
    deriv_filter_gain: 1.0
    saturation: 100.0
    offset: 0.0
    ff_a: 240.0
    ff_b: 0.0
    ff_c: 0.0
    enabled: true
  lin_y:
    kp: 100.0
    ki: 0.0
    kd: 0.0
    antiwindup: true
    integrator_clamp: 20.0
    deriv_filter: true
    deriv_filter_alpha: 5.0
    deriv_filter_gain: 1.0
    saturation: 300.0
    offset: 0.0
    ff_a: 0.0
    ff_b: 0.0
    ff_c: 0.0
    enabled: false
  lin_z:
    kp: 50.0
    ki: 14.0
    kd: 8.0
    antiwindup: true
    integrator_clamp: 70.0
    deriv_filter: false
    deriv_filter_alpha: 0.0
    deriv_filter_gain: 0.0
    saturation: 70.0
    offset: 5.0
    ff_a: 0.0
    ff_b: 0.0
    ff_c: 0.0
    enabled: true
  ang_x:
    kp: 0.0
    ki: 0.0
    kd: 0.0
    antiwindup: false
    integrator_clamp: 20.0
    deriv_filter: false
    deriv_filter_alpha: 0.1
    deriv_filter_gain: 1.0
    saturation: 300.0
    offset: 0.0
    ff_a: 0.0
    ff_b: 0.0
    ff_c: 0.0
    enabled: false
  ang_y:
    kp: 0.0
    ki: 0.0
    kd: 0.0
    antiwindup: false
    integrator_clamp: 20.0
    deriv_filter: false
    deriv_filter_alpha: 0.1
    deriv_filter_gain: 1.0
    saturation: 300.0
    offset: 0.0
    ff_a: 0.0
    ff_b: 0.0
    ff_c: 0.0
    enabled: false
  ang_z:
    kp: 20.0
    ki: 0.0
    kd: 7.0
    antiwindup: false
    integrator_clamp: 20.0
    deriv_filter: true
    deriv_filter_alpha: 8.0
    deriv_filter_gain: 1.0
    saturation: 100.0
    offset: 0.0
    ff_a: 100.0
    ff_b: 0.0
    ff_c: 0.0
    enabled: true

position_controllers:
  lin_z:
    kp: 1.65
    ki: 0.0
    kd: 0.135
    antiwindup: true
    integrator_clamp: 20.0
    deriv_filter: true
    deriv_filter_alpha: 10.0 
    deriv_filter_gain: 1.0
    saturation: 0.25
    enabled: true
  ang_z:
    kp: 1.0
    ki: 0.01
    kd: 9.0
    antiwindup: true
    integrator_clamp: 2.0
    deriv_filter: true
    deriv_filter_alpha: 10.0
    deriv_filter_gain: 1.0
    saturation: 0.25
    enabled: false
