---
sensors/external_pressure_sensor:
  depth_covariance: 4.777569474e-08
  depth_offset: -0.594489776266890

sensors/dvl:
  covariance:
    linear_x: 0.000015
    linear_y: 0.000015
    linear_z: 0.05
