FROM osrf/ros:noetic-desktop-full

ENV DEBIAN_FRONTEND=noninteractive \
    SHELL=/bin/zsh

# Core tools + zsh
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-vcstool \
    python3-catkin-tools \
    python3-pip \
    git \
    curl \
    wget \
    zsh \
    fonts-powerline \
    && rm -rf /var/lib/apt/lists/*

# Oh-My-Zsh + Powerlevel10k
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
    && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Zsh plugins
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Configure .zshrc
RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc \
    && sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc \
    && echo 'source /opt/ros/noetic/setup.zsh' >> ~/.zshrc \
    && echo '[ -f /auv_ws/devel/setup.zsh ] && source /auv_ws/devel/setup.zsh' >> ~/.zshrc \
    && echo '' >> ~/.zshrc \
    && echo '# History config (persisted via volume)' >> ~/.zshrc \
    && echo 'export HISTFILE=/root/.zsh_history_dir/.zsh_history' >> ~/.zshrc \
    && echo 'export HISTSIZE=10000' >> ~/.zshrc \
    && echo 'export SAVEHIST=10000' >> ~/.zshrc \
    && echo 'setopt SHARE_HISTORY' >> ~/.zshrc \
    && echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc \
    && mkdir -p /root/.zsh_history_dir

WORKDIR /auv_ws

# Clone third party and sim dependencies to separate location (avoids volume mount conflict)
COPY sim.repos third_party.repos ./
RUN mkdir -p /third_party && \
    vcs import /third_party < sim.repos && \
    vcs import /third_party < third_party.repos && \
    rm sim.repos third_party.repos

# Install ROS dependencies for third party packages and auv_software
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ros-noetic-vision-msgs \
    ros-noetic-ros-control \
    ros-noetic-ros-controllers \
    ros-noetic-robot-state-publisher \
    ros-noetic-joint-state-publisher \
    ros-noetic-joy \
    ros-noetic-xacro \
    ros-noetic-rosfmt \
    ros-noetic-smach-ros \
    ros-noetic-rosserial-python \
    ros-noetic-move-base \
    ros-noetic-pcl-ros \
    ros-noetic-pcl-conversions \
    ros-noetic-robot-localization && \
    rosdep update && \
    rosdep install --from-paths /third_party --ignore-src -r -y && \
    rm -rf /var/lib/apt/lists/*

# Create symlink so catkin can find third party packages
RUN mkdir -p /auv_ws/src && ln -s /third_party /auv_ws/src/third_party

# Build dependencies (sim + third_party)
RUN . /opt/ros/noetic/setup.sh && \
    catkin config --extend /opt/ros/noetic && \
    catkin build -j4
