created_at: '2026-07-01T01:35:25.799801'
paths:
- name: path1
  ref_a: gate_exit
  ref_b: bin_basket_front_link_kde
  b_mode: 1
  b_reference_distance: 12.0
  waypoint_prefix: path
  waypoints:
  - x: 4.04
    y: -4.02
    z: -1.0
    yaw: 13.999999999999998
- name: path2
  ref_a: bin_exit
  ref_b: ''
  b_mode: 0
  b_reference_distance: 12.0
  waypoint_prefix: path
  waypoints:
  - x: 0.0
    y: 4.720000000000001
    z: -1.0
    yaw: 0.0
