#!/usr/bin/env python3

"""
Simulation ground truth bounding box & segmentation node.

Replaces YOLO tracker inference in simulation by publishing YoloResult messages
derived from Gazebo ground truth model poses. Projects 3D object positions into
each camera's image plane using pinhole geometry and publishes pixel-space
bounding boxes on the same topics the real trackers use.

For the bottom_seg camera, full segmentation masks are generated by projecting
mesh triangle faces and rasterising them with cv2.fillConvexPoly.

Topics published:
  /yolo_result_front, /yolo_result_bottom, /yolo_result_torpedo   (YoloResult)
  /yolo_image_front, /yolo_image_bottom, /yolo_image_torpedo       (annotated Image)
  /yolo_result_seg, /yolo_image_seg                                 (segmentation)
"""

import os
import threading
import rospy
import cv2
import numpy as np

from collections import deque
from cv_bridge import CvBridge
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from ultralytics_ros.msg import YoloResult
from vision_msgs.msg import (
    Detection2DArray,
    Detection2D,
    ObjectHypothesisWithPose,
    BoundingBox2D,
)
from geometry_msgs.msg import Pose, Pose2D, Transform
from sensor_msgs.msg import Image, CameraInfo
from gazebo_msgs.msg import ModelStates

import rospkg
import xml.etree.ElementTree as ET

import tf2_ros
import tf.transformations as tft


@dataclass
class MeshGeometry:
    vertices_h: np.ndarray
    triangles: np.ndarray

    def __post_init__(self):
        self.vertices_h = np.ascontiguousarray(self.vertices_h, dtype=np.float64)
        self.triangles = np.ascontiguousarray(self.triangles, dtype=np.int32)


@dataclass
class SimObject:
    class_id: int
    name: str
    cameras: List[str]
    gazebo_model: str
    offset: Optional[np.ndarray] = None
    boundary: Optional[List[np.ndarray]] = None
    mesh: Optional[MeshGeometry] = None
    match_prefix: bool = False
    boundary_h: Optional[np.ndarray] = field(init=False, default=None, repr=False)

    def __post_init__(self):
        if (self.boundary is None) == (self.mesh is None):
            raise ValueError("SimObject needs exactly one of boundary or mesh")
        if self.boundary is not None and self.offset is None:
            raise ValueError("SimObject with boundary requires an offset")
        if self.boundary is not None:
            self.offset = np.asarray(self.offset, dtype=np.float64)
            boundary = np.asarray(self.boundary, dtype=np.float64)
            local_points = boundary + self.offset
            self.boundary_h = np.column_stack(
                (local_points, np.ones(local_points.shape[0], dtype=np.float64))
            )


def rect(half_extents: Tuple[float, float, float]) -> List[np.ndarray]:
    axes = [row for row in np.diag(half_extents) if np.any(row)]
    if len(axes) != 2:
        raise ValueError("Exactly two non-zero half-extents required")
    return [sx * axes[0] + sy * axes[1] for sx in [1, -1] for sy in [1, -1]]


def circle(radii: Tuple[float, float, float], n: int = 16) -> List[np.ndarray]:
    axes = [row for row in np.diag(radii) if np.any(row)]
    if len(axes) != 2:
        raise ValueError("Exactly two non-zero radii required")
    return [
        axes[0] * np.cos(t) + axes[1] * np.sin(t)
        for t in np.linspace(0, 2 * np.pi, n, endpoint=False)
    ]


def box(half_x: float, half_y: float, half_z: float) -> List[np.ndarray]:
    return [
        np.array([sx * half_x, sy * half_y, sz * half_z])
        for sx in [1, -1]
        for sy in [1, -1]
        for sz in [1, -1]
    ]


def cylinder(half_extents: Tuple[float, float, float], n: int = 8) -> List[np.ndarray]:
    e = np.array(half_extents)
    for i in range(3):
        j, k = [x for x in range(3) if x != i]
        if e[j] == e[k]:
            a0, a1, h = np.zeros(3), np.zeros(3), np.zeros(3)
            a0[j], a1[k], h[i] = e[j], e[k], e[i]
            return [
                a0 * np.cos(t) + a1 * np.sin(t) + s * h
                for s in [1, -1]
                for t in np.linspace(0, 2 * np.pi, n, endpoint=False)
            ]
    raise ValueError("Exactly two equal half-extents (radii) required")


def _parse_dae(model_path: str) -> Tuple[ET.Element, str, np.ndarray]:
    rp = rospkg.RosPack()
    dae_path = os.path.join(rp.get_path("auv_sim_description"), model_path)
    collada_ns = "http://www.collada.org/2005/11/COLLADASchema"
    ns = {"c": collada_ns}
    tree = ET.parse(dae_path)
    root = tree.getroot()

    transform = np.eye(4)
    for node in root.findall(".//c:visual_scene//c:node", ns):
        node_name = node.attrib.get("name", "").lower()
        if "camera" in node_name or "light" in node_name:
            continue
        mat_el = node.find("c:matrix", ns)
        if mat_el is not None and mat_el.text is not None:
            vals = [float(x) for x in mat_el.text.split()]
            mat = np.array(vals).reshape(4, 4)
            if not np.allclose(mat, np.eye(4)):
                transform = transform @ mat

    return root, collada_ns, transform


def load_dae_mesh(model_path: str) -> MeshGeometry:
    try:
        root, collada_ns, transform = _parse_dae(model_path)
    except (rospkg.ResourceNotFound, FileNotFoundError):
        rospy.logwarn(f"DAE model not found: {model_path} — segmentation disabled")
        return MeshGeometry(np.empty((0, 4)), np.empty((0, 3), dtype=np.int32))
    ns = {"c": collada_ns}

    all_vertices = []
    all_triangles = []
    vertex_offset = 0
    for geometry in root.findall(".//c:geometry", ns):
        mesh = geometry.find("c:mesh", ns)
        if mesh is None:
            continue
        pos_array = None
        for src in mesh.findall("c:source", ns):
            fa = src.find("c:float_array", ns)
            if (
                fa is not None
                and fa.text is not None
                and "position" in fa.attrib.get("id", "").lower()
            ):
                pos_array = np.array([float(x) for x in fa.text.split()]).reshape(-1, 3)
                break
        if pos_array is None:
            continue
        transformed = (
            np.column_stack((pos_array, np.ones(pos_array.shape[0], dtype=np.float64)))
            @ transform.T
        )
        geometry_triangles = []
        for tri in mesh.findall("c:triangles", ns):
            p_el = tri.find("c:p", ns)
            if p_el is None or p_el.text is None:
                continue
            indices = np.fromstring(p_el.text, sep=" ", dtype=np.int32)
            stride = len(tri.findall("c:input", ns))
            count = int(tri.attrib.get("count", 0))
            if stride == 0 or indices.size == 0 or count == 0:
                continue
            # Reshape indices to triangles and limit to the specified count
            tri_indices_all = indices.reshape(-1, stride)[:, 0].reshape(-1, 3)
            # Use only the specified number of triangles
            tri_indices = tri_indices_all[:count]
            geometry_triangles.append(tri_indices + vertex_offset)
        if geometry_triangles:
            all_vertices.append(transformed)
            all_triangles.extend(geometry_triangles)
            vertex_offset += transformed.shape[0]

    if not all_vertices:
        return MeshGeometry(np.empty((0, 4)), np.empty((0, 3), dtype=np.int32))

    return MeshGeometry(np.vstack(all_vertices), np.vstack(all_triangles))


def pose_to_matrix(pose: Pose) -> np.ndarray:
    p, o = pose.position, pose.orientation
    return tft.translation_matrix((p.x, p.y, p.z)) @ tft.quaternion_matrix(
        (o.x, o.y, o.z, o.w)
    )


def transform_to_matrix(transform: Transform) -> np.ndarray:
    t, r = transform.translation, transform.rotation
    return tft.translation_matrix((t.x, t.y, t.z)) @ tft.quaternion_matrix(
        (r.x, r.y, r.z, r.w)
    )


def invert_rigid_transform(matrix: np.ndarray) -> np.ndarray:
    inv = np.eye(4)
    rot = matrix[:3, :3]
    trans = matrix[:3, 3]
    inv[:3, :3] = rot.T
    inv[:3, 3] = -rot.T @ trans
    return inv


def project_object(
    points_h: np.ndarray,
    full_tf: np.ndarray,
    intrinsics: Tuple[float, float, float, float],
    image_w: int,
    image_h: int,
) -> Optional[Tuple[float, float, float, float]]:
    """Project 3D local-frame boundary points to a 2D axis-aligned bounding box.

    Transforms each point into the camera frame via pinhole projection and
    returns the AABB of the projected points.

    Args:
        points_h: homogeneous local-frame boundary positions.
        full_tf: 4x4 local-to-camera-optical transform.
        intrinsics: (fx, fy, cx, cy).
        image_w: image width in pixels.
        image_h: image height in pixels.

    Returns:
        (center_x, center_y, size_x, size_y) in pixels, or None if not visible.
    """
    fx, fy, cx, cy = intrinsics

    points_camera = points_h @ full_tf.T
    depths = points_camera[:, 2]
    if np.any(depths <= 0.0):
        return None

    us = fx * points_camera[:, 0] / depths + cx
    vs = fy * points_camera[:, 1] / depths + cy

    u_min, u_max = float(us.min()), float(us.max())
    v_min, v_max = float(vs.min()), float(vs.max())

    # Cull only if the bbox has zero overlap with the image
    if u_max < 0 or u_min >= image_w or v_max < 0 or v_min >= image_h:
        return None

    return (u_min + u_max) / 2, (v_min + v_max) / 2, u_max - u_min, v_max - v_min


def make_detection(
    class_id: int, cx: float, cy: float, sx: float, sy: float
) -> Detection2D:
    det = Detection2D()
    hyp = ObjectHypothesisWithPose()
    hyp.id = class_id
    hyp.score = 1.0
    det.results.append(hyp)
    det.bbox = BoundingBox2D()
    det.bbox.center = Pose2D(x=cx, y=cy, theta=0.0)
    det.bbox.size_x = sx
    det.bbox.size_y = sy
    return det


def render_segmentation_mask(
    mesh: MeshGeometry,
    full_tf: np.ndarray,
    intrinsics: Tuple[float, float, float, float],
    image_w: int,
    image_h: int,
) -> Optional[Tuple[np.ndarray, Tuple[float, float, float, float]]]:
    if mesh.triangles.size == 0:
        return None

    fx, fy, cx, cy = intrinsics
    points_camera = mesh.vertices_h @ full_tf.T
    depths = points_camera[:, 2]
    positive_depth = depths > 0.0
    if not np.any(positive_depth):
        return None

    us = np.empty_like(depths)
    vs = np.empty_like(depths)
    us.fill(np.nan)
    vs.fill(np.nan)
    us[positive_depth] = (
        fx * points_camera[positive_depth, 0] / depths[positive_depth] + cx
    )
    vs[positive_depth] = (
        fy * points_camera[positive_depth, 1] / depths[positive_depth] + cy
    )

    visible_tris = np.all(positive_depth[mesh.triangles], axis=1)
    if not np.any(visible_tris):
        return None

    tri_points = np.rint(
        np.stack((us[mesh.triangles], vs[mesh.triangles]), axis=-1)
    ).astype(np.int32)[visible_tris]
    tri_us = tri_points[:, :, 0]
    tri_vs = tri_points[:, :, 1]
    overlaps_image = ~(
        (tri_us.max(axis=1) < 0)
        | (tri_us.min(axis=1) >= image_w)
        | (tri_vs.max(axis=1) < 0)
        | (tri_vs.min(axis=1) >= image_h)
    )
    if not np.any(overlaps_image):
        return None

    tri_points = tri_points[overlaps_image]
    tri_us = tri_us[overlaps_image]
    tri_vs = tri_vs[overlaps_image]

    mask = np.zeros((image_h, image_w), dtype=np.uint8)
    for tri in tri_points:
        cv2.fillConvexPoly(mask, tri, 255)

    u_min_all = float(tri_us.min())
    u_max_all = float(tri_us.max())
    v_min_all = float(tri_vs.min())
    v_max_all = float(tri_vs.max())
    bcx = (u_min_all + u_max_all) / 2.0
    bcy = (v_min_all + v_max_all) / 2.0
    return mask, (bcx, bcy, u_max_all - u_min_all, v_max_all - v_min_all)


class GazeboInterface:
    _BUFFER_SIZE = 100

    def __init__(self, robot_name: str):
        self.robot_name = robot_name
        self.model_poses: Dict[str, Pose] = {}
        self.model_matrices: Dict[str, np.ndarray] = {}
        self._pose_buffer: deque = deque(maxlen=self._BUFFER_SIZE)
        self._state_lock = threading.Lock()

        rospy.Subscriber(
            "/gazebo/model_states", ModelStates, self._model_states_cb, queue_size=1
        )

    def _model_states_cb(self, msg: ModelStates):
        poses = dict(zip(msg.name, msg.pose))
        matrices = {name: pose_to_matrix(pose) for name, pose in poses.items()}
        with self._state_lock:
            self._pose_buffer.append((rospy.Time.now(), poses, matrices))
            self.model_poses = poses
            self.model_matrices = matrices

    def snapshot_at_time(
        self, stamp: rospy.Time
    ) -> Tuple[Dict[str, Pose], Dict[str, np.ndarray]]:
        """Return the buffered model snapshot closest to *stamp*."""
        with self._state_lock:
            if not self._pose_buffer:
                return self.model_poses, self.model_matrices
            snapshot = min(
                tuple(self._pose_buffer),
                key=lambda entry: abs((entry[0] - stamp).to_sec()),
            )
        _, poses, matrices = snapshot
        return poses, matrices


class SimCamera:
    def __init__(
        self,
        name: str,
        image_topic: str,
        camera_info_topic: str,
        optical_frame: str,
        base_frame: str,
        result_topic: str,
        image_out_topic: str,
        tf_buffer: tf2_ros.Buffer,
        gazebo: "GazeboInterface",
        objects: List[SimObject],
    ):
        self.name = name
        self.optical_frame = optical_frame
        self.base_frame = base_frame
        self.tf_buffer = tf_buffer
        self.bridge = CvBridge()
        self.gazebo = gazebo
        self.objects = objects
        self.class_names: Dict[int, str] = {obj.class_id: obj.name for obj in objects}

        self.intrinsics: Optional[Tuple[float, float, float, float]] = None
        self.image_w = 0
        self.image_h = 0

        self._base_to_camera: Optional[np.ndarray] = None
        self._debug_thread: Optional[threading.Thread] = None
        self._debug_lock = threading.Lock()

        self.result_pub = rospy.Publisher(result_topic, YoloResult, queue_size=1)
        self.image_pub = rospy.Publisher(image_out_topic, Image, queue_size=1)

        rospy.Subscriber(camera_info_topic, CameraInfo, self._info_cb, queue_size=1)
        rospy.Subscriber(
            image_topic, Image, self._image_cb, queue_size=1, buff_size=2**24
        )

    def _info_cb(self, msg: CameraInfo):
        self.intrinsics = (msg.K[0], msg.K[4], msg.K[2], msg.K[5])
        self.image_w = msg.width
        self.image_h = msg.height

    def _image_cb(self, msg: Image):
        if self.intrinsics is None:
            return

        base_to_camera = self._get_base_to_camera()
        if base_to_camera is None:
            return

        # Select the model_states snapshot closest to the image's capture
        # time so that projected bboxes match the rendered viewpoint.
        model_poses, model_matrices = self.gazebo.snapshot_at_time(msg.header.stamp)

        robot_matrix = model_matrices.get(self.gazebo.robot_name)
        if robot_matrix is None:
            return

        robot_matrix_inv = invert_rigid_transform(robot_matrix)
        world_to_camera = base_to_camera @ robot_matrix_inv

        stamp = msg.header.stamp
        detections: List[Detection2D] = []
        masks: List[Image] = []

        for obj in self.objects:
            if obj.match_prefix:
                model_names = [
                    name for name in model_poses if name.startswith(obj.gazebo_model)
                ]
            else:
                model_names = [obj.gazebo_model]

            for model_name in model_names:
                model_matrix = model_matrices.get(model_name)
                if model_matrix is None:
                    continue
                full_tf = world_to_camera @ model_matrix

                if obj.mesh is not None:
                    result = render_segmentation_mask(
                        obj.mesh,
                        full_tf,
                        self.intrinsics,
                        self.image_w,
                        self.image_h,
                    )
                    if result is not None:
                        mask_img, (bcx, bcy, bsx, bsy) = result
                        detections.append(
                            make_detection(obj.class_id, bcx, bcy, bsx, bsy)
                        )
                        mask_msg = self.bridge.cv2_to_imgmsg(mask_img, "mono8")
                        mask_msg.header.stamp = stamp
                        masks.append(mask_msg)
                else:
                    if obj.boundary_h is None:
                        continue
                    result = project_object(
                        obj.boundary_h,
                        full_tf,
                        self.intrinsics,
                        self.image_w,
                        self.image_h,
                    )
                    if result is not None:
                        detections.append(make_detection(obj.class_id, *result))
                        masks.append(Image())

        # Publish YoloResult with the image's own timestamp
        result_msg = YoloResult()
        result_msg.header.stamp = stamp
        result_msg.detections = Detection2DArray()
        result_msg.detections.header.stamp = stamp
        result_msg.detections.detections = detections
        result_msg.masks = masks
        self.result_pub.publish(result_msg)

        if self.image_pub.get_num_connections() > 0:
            self._start_debug_publish(msg, detections, masks, stamp)

    def _start_debug_publish(
        self,
        msg: Image,
        detections: List[Detection2D],
        masks: List[Image],
        stamp: rospy.Time,
    ):
        with self._debug_lock:
            if self._debug_thread is not None and self._debug_thread.is_alive():
                return
            self._debug_thread = threading.Thread(
                target=self._publish_debug_image,
                args=(msg, detections, masks, stamp),
                daemon=True,
            )
            self._debug_thread.start()

    def _publish_debug_image(
        self,
        msg: Image,
        detections: List[Detection2D],
        masks: List[Image],
        stamp: rospy.Time,
    ):
        try:
            cv_image = self.bridge.imgmsg_to_cv2(msg, "bgr8")
            self._draw_detections(cv_image, detections)
            if masks:
                self._draw_seg_masks(cv_image, detections, masks)
            out_msg = self.bridge.cv2_to_imgmsg(cv_image, "bgr8")
            out_msg.header.stamp = stamp
            self.image_pub.publish(out_msg)
        except Exception as e:
            rospy.logwarn_throttle(5, f"[{self.name}] annotation error: {e}")

    def _get_base_to_camera(self) -> Optional[np.ndarray]:
        """Look up and cache the static base_link → optical_link transform."""
        if self._base_to_camera is not None:
            return self._base_to_camera

        try:
            tf_msg = self.tf_buffer.lookup_transform(
                self.optical_frame, self.base_frame, rospy.Time(0), rospy.Duration(2.0)
            )
            self._base_to_camera = transform_to_matrix(tf_msg.transform)
            rospy.loginfo(
                f"[{self.name}] cached static TF: {self.base_frame} → {self.optical_frame}"
            )
            return self._base_to_camera
        except (
            tf2_ros.LookupException,
            tf2_ros.ConnectivityException,
            tf2_ros.ExtrapolationException,
        ) as e:
            rospy.logwarn_throttle(5, f"[{self.name}] static TF not yet available: {e}")
            return None

    def _draw_detections(self, image: np.ndarray, detections: List[Detection2D]):
        for det in detections:
            if not det.results:
                continue
            cx, cy = int(det.bbox.center.x), int(det.bbox.center.y)
            w, h = int(det.bbox.size_x), int(det.bbox.size_y)
            x1, y1 = cx - w // 2, cy - h // 2
            x2, y2 = cx + w // 2, cy + h // 2
            label = self.class_names.get(det.results[0].id, str(det.results[0].id))
            cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(
                image,
                f"SIM {label}",
                (x1, y1 - 5),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                (0, 255, 0),
                1,
            )

    def _draw_seg_masks(
        self,
        image: np.ndarray,
        detections: List[Detection2D],
        masks: List[Image],
    ):
        """Overlay segmentation masks as translucent colored regions."""
        seg_colors = {0: (0, 200, 255), 1: (255, 100, 200)}  # bottle=yellow, ladle=pink
        overlay = image.copy()
        any_drawn = False
        for det, mask_msg in zip(detections, masks):
            if mask_msg.height == 0 or mask_msg.width == 0:
                continue
            mask = self.bridge.imgmsg_to_cv2(mask_msg, "mono8")
            if mask.shape[:2] != image.shape[:2]:
                continue
            class_id = det.results[0].id if det.results else -1
            overlay[mask > 127] = seg_colors.get(class_id, (0, 255, 0))
            any_drawn = True
        if any_drawn:
            cv2.addWeighted(overlay, 0.35, image, 0.65, 0, image)


class SimBboxNode:
    def __init__(self):
        rospy.init_node("sim_bbox_node")

        ns = rospy.get_param("~namespace", "taluy")

        self.tf_buffer = tf2_ros.Buffer()
        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer)

        base_frame = f"{ns}/base_link"

        self.gazebo = GazeboInterface(robot_name=ns)

        # Gate signs — 0.3048 m (1 ft) square, face in YZ plane
        gate_sign = rect((0, 0.3048 / 2, 0.3048 / 2))

        # Torpedo map panel — 0.6096 m (2 ft) square, face in YZ plane
        torp_map = rect((0, 0.3048, -0.3048))

        # Torpedo holes — 0.125 m diameter circles, 16-point circumference
        torp_hole = circle((0, 0.125 / 2, 0.125 / 2))

        # Slalom pipes — vertical cylinders, radius 0.0127 m, height 0.9 m
        pipe_boundary = cylinder((0.0127, 0.0127, 0.45))

        # Bin — full structure for front camera, two squares for bottom camera
        # Face in XZ plane of model (normal along Y)
        # bin_whole: `-_-` cross-section — narrow base, wide overhang.
        # Base/walls (Y ≈ 0.005): X ±0.315, Z ±0.162 from center
        # Overhang   (Y ≈ 0.156): X ±0.457, Z ±0.305 from center
        dy_base = np.array([0.0, -0.076, 0.0])  # base Y offset from center
        dy_ovhg = np.array([0.0, 0.075, 0.0])  # overhang Y offset from center
        bin_whole = [dy_base + bp for bp in rect((0.315, 0, 0.162))] + [
            dy_ovhg + bp for bp in rect((0.457, 0, 0.305))
        ]
        bin_square = rect((0.3048 / 2, 0, 0.3048 / 2))  # each marker: ~1 ft square

        all_objects: List[SimObject] = [
            SimObject(
                class_id=0,
                name="sawfish",
                cameras=["front", "realsense"],
                gazebo_model="robosub_gate",
                offset=np.array([0.0, -0.762, 1.356]),
                boundary=gate_sign,
            ),
            SimObject(
                class_id=1,
                name="shark",
                cameras=["front", "realsense"],
                gazebo_model="robosub_gate",
                offset=np.array([0.0, 0.762, 1.356]),
                boundary=gate_sign,
            ),
            SimObject(
                class_id=4,
                name="torpedo_map",
                cameras=["front", "realsense"],
                gazebo_model="robosub_torpedo",
                offset=np.array([-0.1166, 0.6472, -0.9490]),
                boundary=torp_map,
            ),
            # Both published as ID 5 — the pose estimator sorts upper/lower
            # by image Y position.
            SimObject(
                class_id=5,
                name="torpedo_hole",
                cameras=["torpedo"],
                gazebo_model="robosub_torpedo",
                offset=np.array([-0.1166, 0.6089, -0.9687]),
                boundary=torp_hole,
            ),
            SimObject(
                class_id=5,
                name="torpedo_hole",
                cameras=["torpedo"],
                gazebo_model="robosub_torpedo",
                offset=np.array([-0.1166, 0.8619, -1.0787]),
                boundary=torp_hole,
            ),
        ]

        # Each slalom model has: left_white (-1.5,0,0.45),
        # red (0,0,0.45), right_white (1.5,0,0.45) in model frame.
        slalom_pipes = [
            (3, "white_pipe", np.array([-1.5, 0.0, 0.45])),
            (2, "red_pipe", np.array([0.0, 0.0, 0.45])),
            (3, "white_pipe", np.array([1.5, 0.0, 0.45])),
        ]
        for i in range(1, 4):
            for class_id, name, offset in slalom_pipes:
                all_objects.append(
                    SimObject(
                        class_id=class_id,
                        name=name,
                        cameras=["front", "realsense"],
                        gazebo_model=f"robosub_slalom_{i}",
                        offset=offset,
                        boundary=pipe_boundary,
                    )
                )

        all_objects.extend(
            [
                SimObject(
                    class_id=6,
                    name="bin_whole",
                    cameras=["front", "realsense"],
                    gazebo_model="robosub_bin",
                    offset=np.array([0.0, 0.0812, 0.9337]),
                    boundary=bin_whole,
                ),
                # Bottom camera markers — class IDs 0/1 are reused
                # (pose estimator has per-camera id_tf_map)
                SimObject(
                    class_id=0,
                    name="bin_sawfish",
                    cameras=["bottom"],
                    gazebo_model="robosub_bin",
                    offset=np.array([-0.1525, 0.0144, 0.9337]),
                    boundary=bin_square,
                ),
                SimObject(
                    class_id=1,
                    name="bin_shark",
                    cameras=["bottom"],
                    gazebo_model="robosub_bin",
                    offset=np.array([0.1525, 0.0144, 0.9337]),
                    boundary=bin_square,
                ),
            ]
        )

        # Legs (Z < 0.54): XY ±0.32 × ±0.55
        # Basket level (Z ≥ 0.54): baskets only on ±Y (2 and 4),
        #   X extent = table width (±0.305), Y includes baskets (±0.55)
        # Center: (0, 0, 0.347), no rotation in world
        dz_legs = np.array(
            [0.0, 0.0, -0.077]
        )  # leg Z center relative to overall center
        dz_top = np.array(
            [0.0, 0.0, 0.270]
        )  # basket Z center relative to overall center
        oct_boundary = [dz_legs + bp for bp in box(0.32, 0.55, 0.27)] + [
            dz_top + bp for bp in box(0.305, 0.55, 0.076)
        ]
        all_objects.append(
            SimObject(
                class_id=7,
                name="octagon",
                cameras=["front", "realsense"],
                gazebo_model="robosub_octagon",
                offset=np.array([0.0, 0.0, 0.347]),
                boundary=oct_boundary,
            )
        )
        # Octagon table — central flat panel (bottom camera, class 2)
        # octagon_middle: XY ±0.3048 m, Z ≈ 0.645, horizontal face
        all_objects.append(
            SimObject(
                class_id=2,
                name="octagon_table",
                cameras=["bottom"],
                gazebo_model="robosub_octagon",
                offset=np.array([0.0, 0.0, 0.6446]),
                boundary=rect((0.3048, 0.3048, 0)),
            )
        )
        # Octagon bins — 2 baskets on ±Y, top-face corners (bottom camera)
        # basket_2 at (-0.021, +0.432), basket_4 at (-0.021, -0.432)
        # DAE nodes have 90° rotation: local X→world Y, local Y→world -X
        # After rotation: ±0.1715 in X (world), ±0.1175 in Y (world)
        oct_bin_boundary = rect((0.1715, 0.1175, 0))
        all_objects.append(
            SimObject(
                class_id=4,
                name="octagon_bin_yellow",
                cameras=["bottom"],
                gazebo_model="robosub_octagon",
                offset=np.array([-0.021, 0.432, 0.6865]),
                boundary=oct_bin_boundary,
            )
        )
        all_objects.append(
            SimObject(
                class_id=3,
                name="octagon_bin_pink",
                cameras=["bottom"],
                gazebo_model="robosub_octagon",
                offset=np.array([-0.021, -0.432, 0.6865]),
                boundary=oct_bin_boundary,
            )
        )

        # TAC valve station — two valves inside one model.
        # Mesh is an X-axis barrel (radius 0.12m after 0.001 scale).
        # Only the front circular face (mesh X=0.020) is visible; the desk
        # occludes the back.  Offsets point to the front face center.
        #
        # valve_right (higher Z) → front camera
        # RPY (0, π, 0): flange faces +X, YZ circle stays in YZ
        all_objects.append(
            SimObject(
                class_id=8,
                name="valve",
                cameras=["front"],
                gazebo_model="tac_valve",
                offset=np.array([0.560, 0.555, 1.4205]),
                boundary=circle((0, 0.12, 0.12)),
            )
        )
        # valve_front (lower Z) → bottom camera
        # RPY (0, -π/2, π/2): flange faces +Z, YZ circle maps to XY
        all_objects.append(
            SimObject(
                class_id=5,
                name="valve",
                cameras=["bottom"],
                gazebo_model="tac_valve",
                offset=np.array([0.0185, 0.518, 0.930]),
                boundary=circle((0.12, 0.12, 0)),
            )
        )

        bottle_mesh = load_dae_mesh("models/robosub_bottle/meshes/bottle_final1.dae")
        ladle_mesh = load_dae_mesh("models/robosub_ladle/meshes/ladle.dae")
        rospy.loginfo(
            "Seg faces loaded — bottle: %d, ladle: %d"
            % (len(bottle_mesh.triangles), len(ladle_mesh.triangles))
        )

        all_objects.extend(
            [
                SimObject(
                    class_id=0,
                    name="bottle",
                    cameras=["bottom_seg"],
                    gazebo_model="bottle_final1",
                    mesh=bottle_mesh,
                    match_prefix=True,
                ),
                SimObject(
                    class_id=1,
                    name="ladle",
                    cameras=["bottom_seg"],
                    gazebo_model="ladle_final1",
                    mesh=ladle_mesh,
                    match_prefix=True,
                ),
            ]
        )

        objects_by_camera: Dict[str, List[SimObject]] = {
            "front": [],
            "bottom": [],
            "torpedo": [],
            "bottom_seg": [],
            "realsense": [],
        }

        for obj in all_objects:
            for cam in obj.cameras:
                objects_by_camera[cam].append(obj)

        self.cameras: Dict[str, SimCamera] = {
            "front": SimCamera(
                name="front",
                image_topic=f"/{ns}/cameras/cam_front/image_raw",
                camera_info_topic=f"/{ns}/cameras/cam_front/camera_info",
                optical_frame=f"{ns}/base_link/front_camera_optical_link_stabilized",
                base_frame=base_frame,
                result_topic="/yolo_result_front",
                image_out_topic="/yolo_image_front",
                tf_buffer=self.tf_buffer,
                gazebo=self.gazebo,
                objects=objects_by_camera["front"],
            ),
            "bottom": SimCamera(
                name="bottom",
                image_topic=f"/{ns}/cameras/cam_bottom/image_raw",
                camera_info_topic=f"/{ns}/cameras/cam_bottom/camera_info",
                optical_frame=f"{ns}/base_link/bottom_camera_optical_link",
                base_frame=base_frame,
                result_topic="/yolo_result_bottom",
                image_out_topic="/yolo_image_bottom",
                tf_buffer=self.tf_buffer,
                gazebo=self.gazebo,
                objects=objects_by_camera["bottom"],
            ),
            "torpedo": SimCamera(
                name="torpedo",
                image_topic=f"/{ns}/cameras/cam_torpedo/image_raw",
                camera_info_topic=f"/{ns}/cameras/cam_torpedo/camera_info",
                optical_frame=f"{ns}/base_link/torpedo_camera_optical_link",
                base_frame=base_frame,
                result_topic="/yolo_result_torpedo",
                image_out_topic="/yolo_image_torpedo",
                tf_buffer=self.tf_buffer,
                gazebo=self.gazebo,
                objects=objects_by_camera["torpedo"],
            ),
            "bottom_seg": SimCamera(
                name="bottom_seg",
                image_topic=f"/{ns}/cameras/cam_bottom/image_raw",
                camera_info_topic=f"/{ns}/cameras/cam_bottom/camera_info",
                optical_frame=f"{ns}/base_link/bottom_camera_optical_link",
                base_frame=base_frame,
                result_topic="/yolo_result_seg",
                image_out_topic="/yolo_image_seg",
                tf_buffer=self.tf_buffer,
                gazebo=self.gazebo,
                objects=objects_by_camera["bottom_seg"],
            ),
            "realsense": SimCamera(
                name="realsense",
                image_topic=f"/{ns}/camera/color/image_raw",
                camera_info_topic=f"/{ns}/camera/color/camera_info",
                optical_frame=f"{ns}/camera_depth_optical_frame",
                base_frame=base_frame,
                result_topic="/yolo_result_realsense",
                image_out_topic="/yolo_image_realsense",
                tf_buffer=self.tf_buffer,
                gazebo=self.gazebo,
                objects=objects_by_camera["realsense"],
            ),
        }

        rospy.loginfo(
            f"SimBboxNode started — {len(all_objects)} objects, {len(self.cameras)} cameras"
        )

    def run(self):
        rospy.spin()


if __name__ == "__main__":
    try:
        node = SimBboxNode()
        node.run()
    except rospy.ROSInterruptException:
        pass
