#!/usr/bin/env python3

"""
Simulation ground truth bounding box & segmentation node.

Replaces YOLO tracker inference in simulation by publishing YoloResult messages
derived from Gazebo ground truth model poses. Projects 3D object positions into
each camera's image plane using pinhole geometry and publishes pixel-space
bounding boxes on the same topics the real trackers use.

For the bottom_seg camera, full segmentation masks are generated by projecting
mesh triangle faces and rasterising them with cv2.fillConvexPoly.

Topics published:
  /yolo_result_front, /yolo_result_bottom, /yolo_result_torpedo   (YoloResult)
  /yolo_image_front, /yolo_image_bottom, /yolo_image_torpedo       (annotated Image)
  /yolo_result_seg, /yolo_image_seg                                 (segmentation)
"""

import os
import threading
import rospy
import cv2
import numpy as np
import yaml

from collections import deque
from cv_bridge import CvBridge
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from ultralytics_ros.msg import YoloResult
from vision_msgs.msg import (
    Detection2DArray,
    Detection2D,
    ObjectHypothesisWithPose,
    BoundingBox2D,
)
from geometry_msgs.msg import Pose, Pose2D, Transform
from sensor_msgs.msg import Image, CameraInfo
from gazebo_msgs.msg import ModelStates

import rospkg
import xml.etree.ElementTree as ET

import tf2_ros
import tf.transformations as tft


@dataclass
class MeshGeometry:
    vertices_h: np.ndarray
    triangles: np.ndarray

    def __post_init__(self):
        self.vertices_h = np.ascontiguousarray(self.vertices_h, dtype=np.float64)
        self.triangles = np.ascontiguousarray(self.triangles, dtype=np.int32)


@dataclass
class SimObject:
    class_id: int
    name: str
    cameras: List[str]
    gazebo_model: str
    offset: Optional[np.ndarray] = None
    boundary: Optional[List[np.ndarray]] = None
    mesh: Optional[MeshGeometry] = None
    match_prefix: bool = False
    occlusion_mesh: Optional[MeshGeometry] = None
    boundary_h: Optional[np.ndarray] = field(init=False, default=None, repr=False)

    def __post_init__(self):
        if (self.boundary is None) == (self.mesh is None):
            raise ValueError("SimObject needs exactly one of boundary or mesh")
        if self.boundary is not None and self.offset is None:
            raise ValueError("SimObject with boundary requires an offset")
        if self.boundary is not None:
            self.offset = np.asarray(self.offset, dtype=np.float64)
            boundary = np.asarray(self.boundary, dtype=np.float64)
            local_points = boundary + self.offset
            self.boundary_h = np.column_stack(
                (local_points, np.ones(local_points.shape[0], dtype=np.float64))
            )


def rect(half_extents: Tuple[float, float, float]) -> List[np.ndarray]:
    axes = [row for row in np.diag(half_extents) if np.any(row)]
    if len(axes) != 2:
        raise ValueError("Exactly two non-zero half-extents required")
    return [sx * axes[0] + sy * axes[1] for sx in [1, -1] for sy in [1, -1]]


def circle(radii: Tuple[float, float, float], n: int = 16) -> List[np.ndarray]:
    axes = [row for row in np.diag(radii) if np.any(row)]
    if len(axes) != 2:
        raise ValueError("Exactly two non-zero radii required")
    return [
        axes[0] * np.cos(t) + axes[1] * np.sin(t)
        for t in np.linspace(0, 2 * np.pi, n, endpoint=False)
    ]


def box(half_x: float, half_y: float, half_z: float) -> List[np.ndarray]:
    return [
        np.array([sx * half_x, sy * half_y, sz * half_z])
        for sx in [1, -1]
        for sy in [1, -1]
        for sz in [1, -1]
    ]


def cylinder(half_extents: Tuple[float, float, float], n: int = 8) -> List[np.ndarray]:
    e = np.array(half_extents)
    for i in range(3):
        j, k = [x for x in range(3) if x != i]
        if e[j] == e[k]:
            a0, a1, h = np.zeros(3), np.zeros(3), np.zeros(3)
            a0[j], a1[k], h[i] = e[j], e[k], e[i]
            return [
                a0 * np.cos(t) + a1 * np.sin(t) + s * h
                for s in [1, -1]
                for t in np.linspace(0, 2 * np.pi, n, endpoint=False)
            ]
    raise ValueError("Exactly two equal half-extents (radii) required")


def load_dae_mesh(model_path: str) -> MeshGeometry:
    rp = rospkg.RosPack()
    try:
        dae_path = os.path.join(rp.get_path("auv_sim_description"), model_path)
    except rospkg.ResourceNotFound:
        rospy.logwarn(f"DAE model not found: {model_path} — mesh disabled")
        return MeshGeometry(np.empty((0, 4)), np.empty((0, 3), dtype=np.int32))
    if not os.path.isfile(dae_path):
        rospy.logwarn(f"DAE file not found: {dae_path} — mesh disabled")
        return MeshGeometry(np.empty((0, 4)), np.empty((0, 3), dtype=np.int32))

    collada_ns = "http://www.collada.org/2005/11/COLLADASchema"
    ns = {"c": collada_ns}
    root = ET.parse(dae_path).getroot()

    # Build per-geometry transform map from visual_scene nodes.
    # Each <node> with <instance_geometry url="#geom_id"> defines the
    # transform for that geometry.
    geom_transforms: Dict[str, np.ndarray] = {}
    for node in root.findall(".//c:visual_scene//c:node", ns):
        mat_el = node.find("c:matrix", ns)
        if mat_el is None or mat_el.text is None:
            node_tf = np.eye(4)
        else:
            node_tf = np.array([float(x) for x in mat_el.text.split()]).reshape(4, 4)
        for ig in node.findall("c:instance_geometry", ns):
            url = ig.attrib.get("url", "")
            if url.startswith("#"):
                geom_transforms[url[1:]] = node_tf

    all_vertices = []
    all_triangles = []
    vertex_offset = 0
    for geometry in root.findall(".//c:geometry", ns):
        geom_id = geometry.attrib.get("id", "")
        mesh = geometry.find("c:mesh", ns)
        if mesh is None:
            continue
        pos_array = None
        for src in mesh.findall("c:source", ns):
            fa = src.find("c:float_array", ns)
            if (
                fa is not None
                and fa.text is not None
                and "position" in fa.attrib.get("id", "").lower()
            ):
                pos_array = np.array([float(x) for x in fa.text.split()]).reshape(-1, 3)
                break
        if pos_array is None:
            continue
        transform = geom_transforms.get(geom_id, np.eye(4))
        transformed = (
            np.column_stack((pos_array, np.ones(pos_array.shape[0], dtype=np.float64)))
            @ transform.T
        )
        geometry_triangles = []
        for tri in mesh.findall("c:triangles", ns):
            p_el = tri.find("c:p", ns)
            if p_el is None or p_el.text is None:
                continue
            indices = np.fromstring(p_el.text, sep=" ", dtype=np.int32)
            stride = len(tri.findall("c:input", ns))
            count = int(tri.attrib.get("count", 0))
            if stride == 0 or indices.size == 0 or count == 0:
                continue
            tri_indices_all = indices.reshape(-1, stride)[:, 0].reshape(-1, 3)
            tri_indices = tri_indices_all[:count]
            geometry_triangles.append(tri_indices + vertex_offset)
        if geometry_triangles:
            all_vertices.append(transformed)
            all_triangles.extend(geometry_triangles)
            vertex_offset += transformed.shape[0]

    if not all_vertices:
        return MeshGeometry(np.empty((0, 4)), np.empty((0, 3), dtype=np.int32))

    return MeshGeometry(np.vstack(all_vertices), np.vstack(all_triangles))


def pose_to_matrix(pose: Pose) -> np.ndarray:
    p, o = pose.position, pose.orientation
    return tft.translation_matrix((p.x, p.y, p.z)) @ tft.quaternion_matrix(
        (o.x, o.y, o.z, o.w)
    )


def transform_to_matrix(transform: Transform) -> np.ndarray:
    t, r = transform.translation, transform.rotation
    return tft.translation_matrix((t.x, t.y, t.z)) @ tft.quaternion_matrix(
        (r.x, r.y, r.z, r.w)
    )


def invert_rigid_transform(matrix: np.ndarray) -> np.ndarray:
    inv = np.eye(4)
    rot = matrix[:3, :3]
    trans = matrix[:3, 3]
    inv[:3, :3] = rot.T
    inv[:3, 3] = -rot.T @ trans
    return inv


def project_object(
    points_h: np.ndarray,
    full_tf: np.ndarray,
    intrinsics: Tuple[float, float, float, float],
    image_w: int,
    image_h: int,
) -> Optional[Tuple[float, float, float, float, float]]:
    """Project 3D local-frame boundary points to a 2D axis-aligned bounding box.

    Transforms each point into the camera frame via pinhole projection and
    returns the AABB of the projected points.

    Args:
        points_h: homogeneous local-frame boundary positions.
        full_tf: 4x4 local-to-camera-optical transform.
        intrinsics: (fx, fy, cx, cy).
        image_w: image width in pixels.
        image_h: image height in pixels.

    Returns:
        (center_x, center_y, size_x, size_y, mean_depth) in pixels, or None if
        not visible.
    """
    fx, fy, cx, cy = intrinsics

    points_camera = points_h @ full_tf.T
    depths = points_camera[:, 2]
    if np.any(depths <= 0.0):
        return None

    us = fx * points_camera[:, 0] / depths + cx
    vs = fy * points_camera[:, 1] / depths + cy

    u_min, u_max = float(us.min()), float(us.max())
    v_min, v_max = float(vs.min()), float(vs.max())

    # Cull only if the bbox has zero overlap with the image
    if u_max < 0 or u_min >= image_w or v_max < 0 or v_min >= image_h:
        return None

    mean_depth = float(depths.mean())
    return (
        (u_min + u_max) / 2,
        (v_min + v_max) / 2,
        u_max - u_min,
        v_max - v_min,
        mean_depth,
    )


def apply_bbox_occlusion(
    candidates: List[Tuple[float, int, float, float, float, float, str]],
    occlusion_masks: List[Tuple[str, np.ndarray]],
    image_w: int,
    image_h: int,
    min_visible_fraction: float = 0.05,
) -> List[Tuple[int, float, float, float, float]]:
    """Resolve occlusion among bbox candidates and occlusion mesh silhouettes.

    Bbox candidates are sorted near-to-far. Each candidate is checked against
    coverage from (a) closer accepted bboxes and (b) occlusion mesh silhouettes
    from *different* gazebo models (to avoid self-occlusion of coplanar parts).

    Args:
        candidates: list of (depth, class_id, cx, cy, sx, sy, model_name).
        occlusion_masks: list of (model_name, mask) where mask is a uint8 image
            with nonzero pixels for occluding regions.
        image_w: image width in pixels.
        image_h: image height in pixels.
        min_visible_fraction: minimum visible fraction to keep a detection.

    Returns:
        list of (class_id, cx, cy, sx, sy) after occlusion.
    """
    candidates.sort(key=lambda c: c[0])

    # Build per-model occlusion masks lookup
    occ_by_model: Dict[str, np.ndarray] = {}
    for model_name, mask in occlusion_masks:
        if model_name in occ_by_model:
            occ_by_model[model_name] = np.maximum(occ_by_model[model_name], mask)
        else:
            occ_by_model[model_name] = mask.copy()

    # Combined occlusion mask from all models (precomputed, we subtract per-candidate)
    all_occ = np.zeros((image_h, image_w), dtype=np.uint8)
    for mask in occ_by_model.values():
        all_occ[mask > 0] = 255

    bbox_coverage = np.zeros((image_h, image_w), dtype=np.uint8)
    results = []

    for _depth, class_id, cx, cy, sx, sy, model_name in candidates:
        x1 = max(int(cx - sx / 2), 0)
        y1 = max(int(cy - sy / 2), 0)
        x2 = min(int(cx + sx / 2), image_w)
        y2 = min(int(cy + sy / 2), image_h)
        if x1 >= x2 or y1 >= y2:
            continue

        # Build effective coverage for this candidate: bbox coverage from
        # closer objects + occ mesh coverage from OTHER models only
        roi_bbox = bbox_coverage[y1:y2, x1:x2]
        roi_occ = all_occ[y1:y2, x1:x2]
        own_occ = occ_by_model.get(model_name)
        if own_occ is not None:
            roi_own = own_occ[y1:y2, x1:x2]
            # Other models' occlusion = all occ minus own model's occ
            roi_other_occ = roi_occ & ~roi_own
        else:
            roi_other_occ = roi_occ
        roi_combined = roi_bbox | roi_other_occ

        total_pixels = roi_combined.size
        if total_pixels == 0:
            continue

        visible = roi_combined == 0
        if int(visible.sum()) / total_pixels < min_visible_fraction:
            continue

        # Find bounding rect of visible pixels
        visible_rows = np.any(visible, axis=1)
        visible_cols = np.any(visible, axis=0)
        r_min = int(np.argmax(visible_rows))
        r_max = int(len(visible_rows) - 1 - np.argmax(visible_rows[::-1]))
        c_min = int(np.argmax(visible_cols))
        c_max = int(len(visible_cols) - 1 - np.argmax(visible_cols[::-1]))

        new_x1 = x1 + c_min
        new_y1 = y1 + r_min
        new_x2 = x1 + c_max + 1
        new_y2 = y1 + r_max + 1
        results.append(
            (
                class_id,
                (new_x1 + new_x2) / 2.0,
                (new_y1 + new_y2) / 2.0,
                float(new_x2 - new_x1),
                float(new_y2 - new_y1),
            )
        )

        # Fill accepted (shrunk) bbox into bbox coverage
        cv2.rectangle(bbox_coverage, (new_x1, new_y1), (new_x2, new_y2), 255, -1)

    return results


def make_detection(
    class_id: int, cx: float, cy: float, sx: float, sy: float
) -> Detection2D:
    det = Detection2D()
    hyp = ObjectHypothesisWithPose()
    hyp.id = class_id
    hyp.score = 1.0
    det.results.append(hyp)
    det.bbox = BoundingBox2D()
    det.bbox.center = Pose2D(x=cx, y=cy, theta=0.0)
    det.bbox.size_x = sx
    det.bbox.size_y = sy
    return det


def render_segmentation_mask(
    mesh: MeshGeometry,
    full_tf: np.ndarray,
    intrinsics: Tuple[float, float, float, float],
    image_w: int,
    image_h: int,
) -> Optional[Tuple[np.ndarray, Tuple[float, float, float, float]]]:
    if mesh.triangles.size == 0:
        return None

    fx, fy, cx, cy = intrinsics
    points_camera = mesh.vertices_h @ full_tf.T
    depths = points_camera[:, 2]
    positive_depth = depths > 0.0
    if not np.any(positive_depth):
        return None

    us = np.empty_like(depths)
    vs = np.empty_like(depths)
    us.fill(np.nan)
    vs.fill(np.nan)
    us[positive_depth] = (
        fx * points_camera[positive_depth, 0] / depths[positive_depth] + cx
    )
    vs[positive_depth] = (
        fy * points_camera[positive_depth, 1] / depths[positive_depth] + cy
    )

    visible_tris = np.all(positive_depth[mesh.triangles], axis=1)
    if not np.any(visible_tris):
        return None

    tri_points = np.rint(
        np.stack((us[mesh.triangles], vs[mesh.triangles]), axis=-1)
    ).astype(np.int32)[visible_tris]
    tri_us = tri_points[:, :, 0]
    tri_vs = tri_points[:, :, 1]
    overlaps_image = ~(
        (tri_us.max(axis=1) < 0)
        | (tri_us.min(axis=1) >= image_w)
        | (tri_vs.max(axis=1) < 0)
        | (tri_vs.min(axis=1) >= image_h)
    )
    if not np.any(overlaps_image):
        return None

    tri_points = tri_points[overlaps_image]
    tri_us = tri_us[overlaps_image]
    tri_vs = tri_vs[overlaps_image]

    mask = np.zeros((image_h, image_w), dtype=np.uint8)
    for tri in tri_points:
        cv2.fillConvexPoly(mask, tri, 255)

    u_min_all = float(tri_us.min())
    u_max_all = float(tri_us.max())
    v_min_all = float(tri_vs.min())
    v_max_all = float(tri_vs.max())
    bcx = (u_min_all + u_max_all) / 2.0
    bcy = (v_min_all + v_max_all) / 2.0
    return mask, (bcx, bcy, u_max_all - u_min_all, v_max_all - v_min_all)


class GazeboInterface:
    _BUFFER_SIZE = 100

    def __init__(self, robot_name: str):
        self.robot_name = robot_name
        self.model_poses: Dict[str, Pose] = {}
        self.model_matrices: Dict[str, np.ndarray] = {}
        self._pose_buffer: deque = deque(maxlen=self._BUFFER_SIZE)
        self._state_lock = threading.Lock()

        rospy.Subscriber(
            "/gazebo/model_states", ModelStates, self._model_states_cb, queue_size=1
        )

    def _model_states_cb(self, msg: ModelStates):
        poses = dict(zip(msg.name, msg.pose))
        matrices = {name: pose_to_matrix(pose) for name, pose in poses.items()}
        with self._state_lock:
            self._pose_buffer.append((rospy.Time.now(), poses, matrices))
            self.model_poses = poses
            self.model_matrices = matrices

    def snapshot_at_time(
        self, stamp: rospy.Time
    ) -> Tuple[Dict[str, Pose], Dict[str, np.ndarray]]:
        """Return the buffered model snapshot closest to *stamp*."""
        with self._state_lock:
            if not self._pose_buffer:
                return self.model_poses, self.model_matrices
            snapshot = min(
                tuple(self._pose_buffer),
                key=lambda entry: abs((entry[0] - stamp).to_sec()),
            )
        _, poses, matrices = snapshot
        return poses, matrices


class SimCamera:
    def __init__(
        self,
        name: str,
        image_topic: str,
        camera_info_topic: str,
        optical_frame: str,
        base_frame: str,
        result_topic: str,
        image_out_topic: str,
        tf_buffer: tf2_ros.Buffer,
        gazebo: "GazeboInterface",
        objects: List[SimObject],
    ):
        self.name = name
        self.optical_frame = optical_frame
        self.base_frame = base_frame
        self.tf_buffer = tf_buffer
        self.bridge = CvBridge()
        self.gazebo = gazebo
        self.objects = objects
        self.class_names: Dict[int, str] = {obj.class_id: obj.name for obj in objects}

        self.intrinsics: Optional[Tuple[float, float, float, float]] = None
        self.image_w = 0
        self.image_h = 0

        self._base_to_camera: Optional[np.ndarray] = None
        self._debug_thread: Optional[threading.Thread] = None
        self._debug_lock = threading.Lock()

        self.result_pub = rospy.Publisher(result_topic, YoloResult, queue_size=1)
        self.image_pub = rospy.Publisher(image_out_topic, Image, queue_size=1)

        rospy.Subscriber(camera_info_topic, CameraInfo, self._info_cb, queue_size=1)
        rospy.Subscriber(
            image_topic, Image, self._image_cb, queue_size=1, buff_size=2**24
        )

    def _info_cb(self, msg: CameraInfo):
        self.intrinsics = (msg.K[0], msg.K[4], msg.K[2], msg.K[5])
        self.image_w = msg.width
        self.image_h = msg.height

    def _image_cb(self, msg: Image):
        if self.intrinsics is None:
            return

        base_to_camera = self._get_base_to_camera()
        if base_to_camera is None:
            return

        # Select the model_states snapshot closest to the image's capture
        # time so that projected bboxes match the rendered viewpoint.
        model_poses, model_matrices = self.gazebo.snapshot_at_time(msg.header.stamp)

        robot_matrix = model_matrices.get(self.gazebo.robot_name)
        if robot_matrix is None:
            return

        robot_matrix_inv = invert_rigid_transform(robot_matrix)
        world_to_camera = base_to_camera @ robot_matrix_inv

        stamp = msg.header.stamp
        detections: List[Detection2D] = []
        masks: List[Image] = []

        # Bbox candidates: (depth, class_id, cx, cy, sx, sy, model_name)
        bbox_candidates: List[Tuple[float, int, float, float, float, float, str]] = []
        # Occlusion masks: (model_name, rasterized_mask)
        occ_masks: List[Tuple[str, np.ndarray]] = []
        queued_occ_models: set = set()

        for obj in self.objects:
            if obj.match_prefix:
                model_names = [
                    name for name in model_poses if name.startswith(obj.gazebo_model)
                ]
            else:
                model_names = [obj.gazebo_model]

            for model_name in model_names:
                model_matrix = model_matrices.get(model_name)
                if model_matrix is None:
                    continue
                full_tf = world_to_camera @ model_matrix

                if obj.mesh is not None:
                    result = render_segmentation_mask(
                        obj.mesh,
                        full_tf,
                        self.intrinsics,
                        self.image_w,
                        self.image_h,
                    )
                    if result is not None:
                        mask_img, (bcx, bcy, bsx, bsy) = result
                        detections.append(
                            make_detection(obj.class_id, bcx, bcy, bsx, bsy)
                        )
                        mask_msg = self.bridge.cv2_to_imgmsg(mask_img, "mono8")
                        mask_msg.header.stamp = stamp
                        masks.append(mask_msg)
                else:
                    if obj.boundary_h is None:
                        continue
                    result = project_object(
                        obj.boundary_h,
                        full_tf,
                        self.intrinsics,
                        self.image_w,
                        self.image_h,
                    )
                    if result is not None:
                        cx, cy, sx, sy, depth = result
                        bbox_candidates.append(
                            (depth, obj.class_id, cx, cy, sx, sy, model_name)
                        )

                # Queue occlusion mesh once per model instance
                if (
                    obj.occlusion_mesh is not None
                    and model_name not in queued_occ_models
                ):
                    queued_occ_models.add(model_name)
                    occ_result = render_segmentation_mask(
                        obj.occlusion_mesh,
                        full_tf,
                        self.intrinsics,
                        self.image_w,
                        self.image_h,
                    )
                    if occ_result is not None:
                        occ_mask_img, _ = occ_result
                        occ_masks.append((model_name, occ_mask_img))

        # Apply occlusion: sort near-to-far, shrink occluded bboxes
        for class_id, cx, cy, sx, sy in apply_bbox_occlusion(
            bbox_candidates, occ_masks, self.image_w, self.image_h
        ):
            detections.append(make_detection(class_id, cx, cy, sx, sy))
            masks.append(Image())

        # Publish YoloResult with the image's own timestamp
        result_msg = YoloResult()
        result_msg.header.stamp = stamp
        result_msg.detections = Detection2DArray()
        result_msg.detections.header.stamp = stamp
        result_msg.detections.detections = detections
        result_msg.masks = masks
        self.result_pub.publish(result_msg)

        if self.image_pub.get_num_connections() > 0:
            self._start_debug_publish(msg, detections, masks, stamp)

    def _start_debug_publish(
        self,
        msg: Image,
        detections: List[Detection2D],
        masks: List[Image],
        stamp: rospy.Time,
    ):
        with self._debug_lock:
            if self._debug_thread is not None and self._debug_thread.is_alive():
                return
            self._debug_thread = threading.Thread(
                target=self._publish_debug_image,
                args=(msg, detections, masks, stamp),
                daemon=True,
            )
            self._debug_thread.start()

    def _publish_debug_image(
        self,
        msg: Image,
        detections: List[Detection2D],
        masks: List[Image],
        stamp: rospy.Time,
    ):
        try:
            cv_image = self.bridge.imgmsg_to_cv2(msg, "bgr8")
            self._draw_detections(cv_image, detections)
            if masks:
                self._draw_seg_masks(cv_image, detections, masks)
            out_msg = self.bridge.cv2_to_imgmsg(cv_image, "bgr8")
            out_msg.header.stamp = stamp
            self.image_pub.publish(out_msg)
        except Exception as e:
            rospy.logwarn_throttle(5, f"[{self.name}] annotation error: {e}")

    def _get_base_to_camera(self) -> Optional[np.ndarray]:
        """Look up and cache the static base_link → optical_link transform."""
        if self._base_to_camera is not None:
            return self._base_to_camera

        try:
            tf_msg = self.tf_buffer.lookup_transform(
                self.optical_frame, self.base_frame, rospy.Time(0), rospy.Duration(2.0)
            )
            self._base_to_camera = transform_to_matrix(tf_msg.transform)
            rospy.loginfo(
                f"[{self.name}] cached static TF: {self.base_frame} → {self.optical_frame}"
            )
            return self._base_to_camera
        except (
            tf2_ros.LookupException,
            tf2_ros.ConnectivityException,
            tf2_ros.ExtrapolationException,
        ) as e:
            rospy.logwarn_throttle(5, f"[{self.name}] static TF not yet available: {e}")
            return None

    def _draw_detections(self, image: np.ndarray, detections: List[Detection2D]):
        for det in detections:
            if not det.results:
                continue
            cx, cy = int(det.bbox.center.x), int(det.bbox.center.y)
            w, h = int(det.bbox.size_x), int(det.bbox.size_y)
            x1, y1 = cx - w // 2, cy - h // 2
            x2, y2 = cx + w // 2, cy + h // 2
            label = self.class_names.get(det.results[0].id, str(det.results[0].id))
            cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(
                image,
                f"SIM {label}",
                (x1, y1 - 5),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                (0, 255, 0),
                1,
            )

    def _draw_seg_masks(
        self,
        image: np.ndarray,
        detections: List[Detection2D],
        masks: List[Image],
    ):
        """Overlay segmentation masks as translucent colored regions."""
        seg_colors = {0: (0, 200, 255), 1: (255, 100, 200)}  # bottle=yellow, ladle=pink
        overlay = image.copy()
        any_drawn = False
        for det, mask_msg in zip(detections, masks):
            if mask_msg.height == 0 or mask_msg.width == 0:
                continue
            mask = self.bridge.imgmsg_to_cv2(mask_msg, "mono8")
            if mask.shape[:2] != image.shape[:2]:
                continue
            class_id = det.results[0].id if det.results else -1
            overlay[mask > 127] = seg_colors.get(class_id, (0, 255, 0))
            any_drawn = True
        if any_drawn:
            cv2.addWeighted(overlay, 0.35, image, 0.65, 0, image)


SHAPE_FACTORIES = {
    "rect": lambda args: rect(tuple(args)),
    "circle": lambda args: circle(tuple(args)),
    "box": lambda args: box(*args),
    "cylinder": lambda args: cylinder(tuple(args)),
}


def _build_boundary(spec) -> List[np.ndarray]:
    """Build boundary points from a YAML boundary spec (single dict or list)."""
    if isinstance(spec, dict):
        return SHAPE_FACTORIES[spec["shape"]](spec["args"])

    # Compound: list of {shape, args, offset}
    points = []
    for part in spec:
        sub_points = SHAPE_FACTORIES[part["shape"]](part["args"])
        sub_offset = np.array(part.get("offset", [0, 0, 0]), dtype=np.float64)
        points.extend(p + sub_offset for p in sub_points)
    return points


def load_config(config_path: str, ns: str) -> Tuple[List[SimObject], Dict]:
    """Load objects and camera configs from a YAML file."""
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    # Build camera configs with namespace substituted
    camera_configs = {}
    for cam_name, cam_cfg in config["cameras"].items():
        camera_configs[cam_name] = {
            k: v.replace("{ns}", ns) for k, v in cam_cfg.items()
        }

    # Build SimObjects
    all_objects: List[SimObject] = []
    for obj_cfg in config["objects"]:
        if "mesh" in obj_cfg:
            mesh = load_dae_mesh(obj_cfg["mesh"])
            rospy.loginfo(
                "Seg faces loaded — %s: %d" % (obj_cfg["name"], len(mesh.triangles))
            )
            all_objects.append(
                SimObject(
                    class_id=obj_cfg["class_id"],
                    name=obj_cfg["name"],
                    cameras=obj_cfg["cameras"],
                    gazebo_model=obj_cfg["gazebo_model"],
                    mesh=mesh,
                    match_prefix=obj_cfg.get("match_prefix", False),
                )
            )
        else:
            boundary = _build_boundary(obj_cfg["boundary"])
            occ_mesh = None
            if "occlusion_mesh" in obj_cfg:
                occ_mesh = load_dae_mesh(obj_cfg["occlusion_mesh"])
                rospy.loginfo(
                    "Occlusion mesh loaded — %s: %d faces"
                    % (obj_cfg["name"], len(occ_mesh.triangles))
                )
            all_objects.append(
                SimObject(
                    class_id=obj_cfg["class_id"],
                    name=obj_cfg["name"],
                    cameras=obj_cfg["cameras"],
                    gazebo_model=obj_cfg["gazebo_model"],
                    offset=np.array(obj_cfg["offset"], dtype=np.float64),
                    boundary=boundary,
                    match_prefix=obj_cfg.get("match_prefix", False),
                    occlusion_mesh=occ_mesh,
                )
            )

    return all_objects, camera_configs


class SimBboxNode:
    def __init__(self):
        rospy.init_node("sim_bbox_node")

        ns = rospy.get_param("~namespace", "taluy")
        default_config = os.path.join(
            rospkg.RosPack().get_path("auv_vision"), "config", "sim_bbox_objects.yaml"
        )
        config_path = rospy.get_param("~config", default_config)

        self.tf_buffer = tf2_ros.Buffer()
        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer)

        base_frame = f"{ns}/base_link"

        self.gazebo = GazeboInterface(robot_name=ns)

        all_objects, camera_configs = load_config(config_path, ns)

        objects_by_camera: Dict[str, List[SimObject]] = {
            cam: [] for cam in camera_configs
        }
        for obj in all_objects:
            for cam in obj.cameras:
                objects_by_camera[cam].append(obj)

        self.cameras: Dict[str, SimCamera] = {}
        for cam_name, cam_cfg in camera_configs.items():
            self.cameras[cam_name] = SimCamera(
                name=cam_name,
                image_topic=cam_cfg["image_topic"],
                camera_info_topic=cam_cfg["camera_info_topic"],
                optical_frame=cam_cfg["optical_frame"],
                base_frame=base_frame,
                result_topic=cam_cfg["result_topic"],
                image_out_topic=cam_cfg["image_out_topic"],
                tf_buffer=self.tf_buffer,
                gazebo=self.gazebo,
                objects=objects_by_camera[cam_name],
            )

        rospy.loginfo(
            f"SimBboxNode started — {len(all_objects)} objects, {len(self.cameras)} cameras"
        )

    def run(self):
        rospy.spin()


if __name__ == "__main__":
    try:
        node = SimBboxNode()
        node.run()
    except rospy.ROSInterruptException:
        pass
