#!/usr/bin/env python3
"""
Viewer for YOLO-pose valve labels generated by sim_auto_labeler.py.

Usage:
    python3 valve_label_viewer.py [--dataset ~/yolo_valve_dataset]
    rosrun auv_vision valve_label_viewer.py

Controls:
    D / Right arrow  — next image
    A / Left arrow   — previous image
    X                — delete current image + label, advance to next
    Q                — quit
"""

import os
import sys
import glob
import argparse
import cv2
import numpy as np

BBOX_COLOR = (220, 180, 0)

# OpenCV raw keycodes for arrow keys (Linux/X11).
KEY_LEFT  = 65361
KEY_RIGHT = 65363


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default=os.path.expanduser("~/yolo_valve_dataset"),
                        help="Path to dataset directory (contains images/ and labels/)")
    return parser.parse_args()


def draw_labels(img, label_path):
    h, w = img.shape[:2]
    if not os.path.exists(label_path):
        return
    with open(label_path) as f:
        for line in f:
            fields = line.strip().split()
            if len(fields) < 5:
                continue
            x_c, y_c, bw, bh = map(float, fields[1:5])
            x1 = int((x_c - bw / 2) * w)
            y1 = int((y_c - bh / 2) * h)
            x2 = int((x_c + bw / 2) * w)
            y2 = int((y_c + bh / 2) * h)
            cv2.rectangle(img, (x1, y1), (x2, y2), BBOX_COLOR, 2)

            kp_data = fields[5:]
            for i in range(0, len(kp_data) - 2, 3):
                kp_x = int(float(kp_data[i])     * w)
                kp_y = int(float(kp_data[i + 1]) * h)
                vis  = int(kp_data[i + 2])
                if vis == 2:
                    img[kp_y:kp_y + 2, kp_x:kp_x + 2] = (255, 0, 0)


def main():
    args = parse_args()
    images_dir = os.path.join(args.dataset, "images")
    labels_dir = os.path.join(args.dataset, "labels")

    image_paths = sorted(glob.glob(os.path.join(images_dir, "*.jpg")))
    if not image_paths:
        print(f"No images found in {images_dir}")
        sys.exit(1)

    print(f"Found {len(image_paths)} images.")
    print("  D / → : next    A / ← : previous    X : delete    Q : quit")

    idx     = 0
    deleted = 0
    win     = "Valve Labels  [ D/→ next | A/← prev | X delete | Q quit ]"
    cv2.namedWindow(win, cv2.WINDOW_NORMAL)

    while image_paths:
        img_path   = image_paths[idx]
        stem       = os.path.splitext(os.path.basename(img_path))[0]
        label_path = os.path.join(labels_dir, stem + ".txt")

        img = cv2.imread(img_path)
        if img is None:
            image_paths.pop(idx)
            idx = min(idx, len(image_paths) - 1)
            continue

        draw_labels(img, label_path)

        status = f"{stem}   {idx + 1} / {len(image_paths)}"
        cv2.putText(img, status, (10, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (200, 200, 200), 1)
        cv2.imshow(win, img)

        key = cv2.waitKey(0)
        ch  = key & 0xFF

        if ch == ord("q"):
            break
        elif ch == ord("d") or key == KEY_RIGHT:
            idx = min(idx + 1, len(image_paths) - 1)
        elif ch == ord("a") or key == KEY_LEFT:
            idx = max(idx - 1, 0)
        elif ch == ord("x"):
            os.remove(img_path)
            if os.path.exists(label_path):
                os.remove(label_path)
            deleted += 1
            print(f"Deleted {stem}")
            image_paths.pop(idx)
            if not image_paths:
                print("No images remaining.")
                break
            idx = min(idx, len(image_paths) - 1)

    cv2.destroyAllWindows()
    print(f"Done. {deleted} image(s) deleted.")


if __name__ == "__main__":
    main()

