# List all the topics here
topics:
  # Commands
  - /turquoise/cmd_vel
  - /turquoise/cmd_depth

  # Sensors
  - /turquoise/sensors/imu/data_raw
  - /turquoise/sensors/imu/data
  - /turquoise/sensors/imu/mag
  - /turquoise/sensors/imu/heading
  - /turquoise/sensors/imu/heading_raw
  - /turquoise/sensors/compass/heading
  - /turquoise/sensors/compass/heading_raw
  - /turquoise/sensors/imu/pressure
  - /turquoise/sensors/pressure
  - /turquoise/sensors/pressure/depth
  - /turquoise/sensors/temperature
  - /turquoise/sensors/sonar_bottom
  - /turquoise/sensors/dvl/velocity
  - /turquoise/sensors/dvl/info
  - /turquoise/sensors/dvl/velocity

  # Battery
  - /turquoise/battery/state

  # Mainboard features
  - /turquoise/board/aux
  - /turquoise/board/odom
  - /turquoise/board/is_timeouted
  - /turquoise/board/is_armed
  - /turquoise/board/cpu_load
  - /turquoise/board/thrusters/input
  - /turquoise/board/thrusters/currents

  # [Deprecated] depth, use odom.
  - /turquoise/depth

  # Odom
  - /turquoise/odom

  # Xavier Stats
  - /turquoise/xavier/cpu_temp
  - /turquoise/xavier/gpu_temp
  - /turquoise/xavier/ram
  - /turquoise/xavier/stats
  - /turquoise/xavier/cores_alive
  - /turquoise/xavier/aux_temp
  - /turquoise/xavier/board_temp
  
  # Cameras
  - /turquoise/cameras/cam_front/image_raw/compressed
  - /turquoise/cameras/cam_bottom/image_raw/compressed

# Set use_prefix to true, to not use output_name and 
# use only output_prefix. In this mode, a date_time 
# will be appended to prefix.
# if use_prefix is set false, then the output_name
# will be used, thus the date_time will not be appended
# and the output_name will be the full name of file.
use_prefix: true

# Output prefix (Use full path, dont use "~", 
# ex: /home/username/path/to/folder)
output_prefix: /home/nvidia/bags/record

# Output Full Name (Use full path, dont use "~", 
# ex: /home/username/path/to/file.bag)
output_name: /home/nvidia/test.bag
