---
# Local Costmap Parameters (inherits from mbf_costmap_common_params.yaml)

local_costmap:
  # Inherit common parameters
  global_frame: odom       # Should match common params (often odom frame)
  robot_base_frame: base_link # Should match common params
  update_frequency: 5.0     # Higher frequency for local map is typical
  publish_frequency: 2.0    # Higher frequency for local map is typical
  transform_tolerance: 0.5  # Should match common params

  # Local map specific parameters
  static_map: false       # Local map usually doesn't use a static map
  rolling_window: true    # Keep the map centered on the robot
  width: 6.0              # meters (Smaller than global map)
  height: 6.0             # meters (Smaller than global map)
  resolution: 0.05        # meters/pixel (Can be finer than global map)

  # Layers - Specify which layers from common params to use, or define new ones
  plugins:
    # Example using VoxelLayer for obstacle detection
    # - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
