---
# Recovery Behaviors Parameters

# List of recovery behavior plugins and their parameters
# The order determines the sequence in which they are tried

# Example: Clear Costmap Recovery (clears obstacles from costmaps)
clear_costmap_recovery:
  reset_distance: 3.0 # How far back to clear obstacles in the costmap (meters)
  layer_names: ["obstacle_layer"] # Specify which layers to clear (adjust if using different layer names)

# Example: Rotate Recovery (rotates the robot in place to clear space)
# rotate_recovery:
#   frequency: 20.0
#   sim_granularity: 0.017
#   tolerance: 0.3

# Add other recovery behaviors as needed (e.g., move_slow_and_clear)
