---
###############################################################################
#                        Move Base Flex Main Configuration                   #
###############################################################################

# ---------------------- Core Timing Parameters -----------------------------
controller_frequency: 10.0       # Hz ─ How often the local planner (controller) runs
planner_frequency: 0.5           # Hz ─ How often the global planner runs

# ---------------------- Recovery Settings -----------------------------------
recovery_enabled: true
recovery_patience: 15.0

# -------------------- Oscillation Detection --------------------------------
oscillation_timeout: 10.0        # sec ─ Time window to detect oscillatory motion
oscillation_distance: 0.2        # m   ─ Min displacement to clear oscillation flag

# ---------------------- Plugin Selection ------------------------------------
# Global Planner (computes nav_msgs/Path on the global costmap)
planner_plugin: "mbf_ompl_global_planner/OMPLPlanner"
planner_max_retries: 3            # retry count if planner fails
planner_patience: 5.0             # sec ─ max time to wait for a plan

# Local Planner / Controller (follows the path, avoids local obstacles)
controller_plugin: "teb_local_planner/TebLocalPlannerROS"
controller_max_retries: 3
controller_patience: 5.0

# -------------------- Recovery Behavior Plugins -----------------------------
# Invoked in order whenever the local planner fails repeatedly
recovery_behaviors:
  - name: clear_costmap_recovery
    type: "clear_costmap_recovery/ClearCostmapRecovery"
    frequency: 1.0
  - name: rotate_recovery
    type: "mbf_recovery/RotateRecovery"
    frequency: 0.5      # slower spin for AUV


###############################################################################
#                      Costmap Common Parameters (costmap_common)            #
###############################################################################
costmap_common:
  # frames
  global_frame: "odom"
  robot_base_frame: "taluy/base_link"
  transform_tolerance: 0.5

  # timing
  update_frequency: 10.0
  publish_frequency: 2.0

  # Robot footprint  (square 1 m × 1 m)
  footprint: [[0.5, 0.5], [0.5, -0.5], [-0.5, -0.5], [-0.5, 0.5]]

  # 3-D costmap parameters (voxel grid)
  map_type: voxel
  origin_z: 0.0
  z_resolution: 0.1                      # m per voxel layer
  z_voxels: 10                           # ⇒ covers 1 m vertically
  unknown_threshold: 9
  mark_threshold: 0


  # Default inflation behaviour (can be overridden below)
  inflation_layer:
    cost_scaling_factor: 5.0
    inflation_radius: 1.0                # m

  # Default voxel-layer sensor (depth cam)
  voxel_layer:
    enabled: true
    observation_sources: depth_camera_source
    depth_camera_source:
      data_type: PointCloud2
      topic: /taluy/depth/points
      marking: true
      clearing: true
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0
      obstacle_range: 5.0                # m
      raytrace_range: 6.0                # m
      sensor_frame: taluy/base_link/depth_camera_link



###############################################################################
#                  Global Costmap Parameters (global_costmap)                #
###############################################################################
global_costmap:
  static_map: false
  rolling_window: false
  resolution: 0.5
  plugins:
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: objects
    objects:
      data_type: PointCloud2
      topic: "/dynamic_objects"
      marking: true
      clearing: true
      expected_update_rate: 5.0
      obstacle_range: 10.0

  inflation_layer:
    inflation_radius: 1.0

###############################################################################
#                   Local Costmap Parameters (local_costmap)                 #
###############################################################################
local_costmap:
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.2
  plugins:
    - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: objects
    objects:
      data_type: PointCloud2
      topic: "/dynamic_objects"
      marking: true
      clearing: true
      expected_update_rate: 5.0
      obstacle_range: 4.0
  inflation_layer:
    inflation_radius: 0.5
