---
create_gate_frames_node:
  gate_frame_1: "gate_blue_arrow_link"
  gate_frame_2: "gate_red_arrow_link"
  offset_add: 1.0      # Offset distance for the outward trajectory frame. The value is added to the gate frame.
  offset_subtract: 1.7      # Offset distance for the inward trajectory frame. The value is subtracted from the gate frame.
