---
gate_frame_1: "gate_shark_link"
gate_frame_2: "gate_sawfish_link"
target_gate_frame: "gate_shark_link"
entrance_offset: 1.0  # Distance (m) to offset the entrance frame along its normal direction
exit_offset: 1.4  # Distance (m) to offset the exit frame along the same normal direction
z_offset: 0.5  # Vertical drop below the gate frame (m)
parallel_shift_offset: 0.15  # Parallel shift offset for entrance and exit frames (m)
# --- COIN FLIP RESCUER FRAME PARAMS ---
wall_reference_yaw: -2.85  # Yaw (in radians), reference direction
rescuer_distance: 1.5    # Distance (m) from vehicle position in reference yaw direction for the frame
