---
odom_frame: "odom"
robot_frame: "taluy/base_link"
torpedo_frame: "torpedo_map_link"

torpedo_closer_frame: "torpedo_close"
torpedo_big_hole_frame: "torpedo_hole_1_link"
torpedo_medium_hole_frame: "torpedo_hole_2_link"
torpedo_front_view_frame: "torpedo_front_view"
torpedo_launch_frame: "torpedo_launch"

closer_frame_distance: 2.25
front_view_distance: 1.75
launch_distance: 0.6
