inspection:
  - taluy/cameras/cam_front/image_rect_color/compressed
  - taluy/cameras/cam_bottom/image_rect_color/compressed
  - taluy/cameras/cam_torpedo/image_raw/compressed

valve:
  - taluy/cameras/cam_front/image_rect_color/compressed
  - keypoint
  - alt keypoint

pipeline:
  - taluy/cameras/cam_bottom/image_rect_color/compressed
  - /pipe_result_debug/compressed
  - /pipe_result_debug_fancy/compressed
