name: base docker images

# scheduled run every day at 00:00 GMT +03:00
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - sencer/add-native-ci-build
  pull_request:
    paths:
      - 'docker/Dockerfile.auv-base'
  schedule:
    - cron: "0 21 * * *"

concurrency:
  group: base_images
  cancel-in-progress: true

jobs:
  build-and-push-base-docker:
    uses: ./.github/workflows/build_and_push_images.yml
    with:
      image_type: base
