---
name: Pre-commit Checks

on:
  workflow_call:

jobs:
  pre-commit:
    name: Run Pre-commit Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y clang-format xmllint

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Check for modifications
        run: git diff --exit-code
