name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  industrial_ci:
    strategy:
      matrix:
        host: [ubuntu-20.04, self-hosted]
    uses: ./.github/workflows/industrial_ci.yml
    with:
      runner: ${{ matrix.host }}
