name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.ref }}
  cancel-in-progress: true

jobs:
  industrial_ci:
    strategy:
      matrix:
        host: [ubuntu-20.04, self-hosted]
    uses: ./.github/workflows/industrial_ci.yml
    with:
      runner: ${{ matrix.host }}
