name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.ref }}
  cancel-in-progress: true

jobs:
  native_ci:
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-20.04, self-hosted]
    uses: ./.github/workflows/industrial_ci.yml
    with:
      runner: ${{ matrix.host }}
      docker_image_tag: ghcr.io/itu-auv/auv-software-base:latest
  
  build-and-push-docker:
    needs: native_ci
    uses: ./.github/workflows/build_and_push_main_images.yml
